### ISSUE TITLE
[Select] Feature request - Select component filter by label option instead of value

### ISSUE THREAD

**Issue by BenSmith123** [adaptui/react#399]
When typing in a Select component, the scrolled-to/highlighted item is chosen based on the **value** of the item, not the **label**`.

i.e. typing the letter 'H' will automatically scroll/highlight an item with a **value** starting with 'H', rather than scrolling/highlighting the item displayed (by label) in the Select component which starts with the letter 'H'.

Scrolling-to/highlighting functionality works as expected when choosing to omit a **value** according to the documentation here: https://github.com/adaptui/react/blob/HEAD/docs/select.md#selectoption but it would be ideal if the Select component were able to still have a **value**

**Comment by navin-moorthy** [comment]
Select component has been deprecated here, kindly use the better & updated [Select component](https://ariakit.org/examples/select) from [Ariakit](https://ariakit.org/examples/select)
